[package]
name = "stardust"
version = "0.1.0"
edition = "2021"

[dependencies]
#  rustyline = "11.0.0"
reedline = "0.19.1" 
anyhow = "1.0.71"
clap = { version = "4.3.0", features = ["derive"] }
log = "0.4.17"
simplelog = "0.12.1"
xdg = "2.5.0"
syn = "2.0.16"
